/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasJframes;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author anton
 */
public class Tablero extends javax.swing.JInternalFrame {
   
   JButton bMatriz[][] = new JButton[8][8];     
      boolean player = true;
      private int columnas;
      private int filas;
      public predicados pre = new predicados();
    public Tablero() {
        initComponents();
          fc_DibujarTablero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl4 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(null);

        lbl4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Jugador1:");

        lbl1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("jLabel2");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        lbl3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Jugador2:");

        lbl2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("jLabel1");

        jButton1.setText("Reiniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl1)
                            .addComponent(lbl4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(lbl3))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     
      
      
              
    }//GEN-LAST:event_jButton1ActionPerformed

  public void fc_DibujarTablero(){
         int contadorfilas = 0;
         int contadorcolumnas =0;
        
        int x = 10;
        int y = 10;
          for(JButton[] ArrBotones : bMatriz){
             
              for(JButton Boton : ArrBotones){
                
                   
                    Boton = new JButton(contadorfilas+","+contadorcolumnas);
                    Boton.setBounds(x, y, 50, 50);
                    Boton.setBackground(java.awt.Color.GRAY);
                    Boton.setName(contadorfilas+","+contadorcolumnas);
                    jPanel1.add(Boton);
                    jPanel1.setLayout(new GridLayout(8,8));
                    x+=60;
                    fc_Ipartida(Boton);
                    JButton btnprueba = Boton;
                    bMatriz[contadorfilas][contadorcolumnas] = btnprueba;
                     int f = contadorfilas;
                     int c = contadorcolumnas;
                    Boton.addActionListener(new java.awt.event.ActionListener() {
                         public void actionPerformed(java.awt.event.ActionEvent evt) {
                             fc_eventoClick(btnprueba, f, c);
                               // setFilas(f);
                               // setColumnas(c);
                         }
                        });   
              contadorcolumnas++;
              
              }
              y =+60;
               contadorcolumnas=0;
             x = 10;
              contadorfilas++;
            
          }
           
          
         
        
    }
  
   public void fc_eventoClick(JButton btn, int f, int c){
      
        
         
         if(btn.getBackground()== java.awt.Color.GRAY && player == true)
         {
             //setFilas(filas);
             btn.setBackground(java.awt.Color.BLACK);
             System.out.println("fila "+f+ "columna" +c);
             player=false;
         }else{
        btn.setBackground(java.awt.Color.WHITE);
         // System.out.println("Turno: Player2");
           player=true;
         }
        
         bMatriz[f][c].setBackground(java.awt.Color.YELLOW);
         //System.out.println("");
         try{
             /*Comprueba que el primer movimiento sea valido para lo jugadores*/

         
             if(pre.esMenorA0().test(f)){
             
             if(pre.especialAbajo(f, c).test(bMatriz)){
                 JOptionPane.showMessageDialog(this,"especialAbajo");
             }
            }
         else if(pre.esMenorA0().test(c)){
              
             if(pre.especialDerecha(f, c).test(bMatriz)){
             JOptionPane.showMessageDialog(this,"especialDerecha");
             }
             
         }else if(pre.esMayorA0().test(c))
         {
         if(pre.EspecialIzq(f, c).test(bMatriz))
         {
          JOptionPane.showMessageDialog(this,"EspecialIzquierda");
         }
         
         }else if(pre.esMayorA0().test(f))
         {
             if(pre.especialArriba(f, c).test(bMatriz))
             {
              JOptionPane.showMessageDialog(this,"EspecialArriba");
             }
         }
         else if(pre.sepuedejugar(f,c).test(bMatriz))
         {
             JOptionPane.showMessageDialog(this,"No puedes jugar en esa posicion");
         }
         
        
         
         
         
        
         
         
         
         
         }catch(Exception erro)
         {
             JOptionPane.showMessageDialog(this,"Error");
         
         }
       
     }
   
   public void fc_Ipartida(JButton btn)
   {
       System.out.println(btn.getName());
   if(btn.getName().equals("3,3"))
   {
    
   btn.setBackground(Color.WHITE);
   
   }else if(btn.getName().equals("4,4"))
   {
    btn.setBackground(Color.WHITE);
   }
   
   if(btn.getName().equals("3,4"))
   {
    btn.setBackground(Color.BLACK);
   }else if(btn.getName().equals("4,3"))
   {
    btn.setBackground(Color.BLACK);
   }
   }
   
   public void fc_pintarTurnos(JButton btn,int contfilas, int contcolum)
   {
       
   
   }
    /**
     * @return the columnas
     */
    public int getColumnas() {
        return columnas;
    }

    /**
     * @param columnas the columnas to set
     */
    public void setColumnas(int columnas) {
        this.columnas = columnas;
    }

    /**
     * @return the filas
     */
    public int getFilas() {
        return filas;
    }

    /**
     * @param filas the filas to set
     */
    public void setFilas(int filas) {
        this.filas = filas;
    }

    /**
     * Creates new form Tablero
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    // End of variables declaration//GEN-END:variables
}
